
--PROJECT AIRLINE MANAGER

--CLEAN UP SCRIPT
set serveroutput on
declare
    v_table_exists varchar(1) := 'Y';
    v_sql varchar(2000);
begin
   dbms_output.put_line('Start schema cleanup');
   for i in (select 'AIRLINE' table_name from dual union all
             select 'ACCOUNT' table_name from dual union all
             select 'AIRCRAFT' table_name from dual union all
             select 'FUEL' table_name from dual union all
             select 'CO2' table_name from dual union all
             select 'AC_OWNED' table_name from dual union all
             select 'AIRPORT' table_name from dual union all
             select 'ROUTES' table_name from dual union all
             select 'HANGAR' table_name from dual union all
             select 'HUB' table_name from dual

   )
   loop
   dbms_output.put_line('....Dropping table '||i.table_name);
   begin
       select 'Y' into v_table_exists
       from USER_TABLES
       where TABLE_NAME=i.table_name;

       v_sql := 'drop table '||i.table_name || ' cascade constraints';
       execute immediate v_sql;
       dbms_output.put_line('........Table '||i.table_name||' dropped successfully');
       
   exception
       when no_data_found then
           dbms_output.put_line('........Table already dropped');
   end;
   end loop;
   dbms_output.put_line('Schema cleanup successfully completed');
exception
   when others then
      dbms_output.put_line('Failed to execute code:'||sqlerrm);
end;
/
create table AIRLINE(NAME varchar2(10), id number GENERATED BY DEFAULT AS IDENTITY, PRIMARY KEY(id));
create table ACCOUNT(BALANCE number, id number GENERATED BY DEFAULT AS IDENTITY, PRIMARY KEY(id), airline_id number, FOREIGN KEY(airline_id) REFERENCES AIRLINE(id));
create table AIRCRAFT(id number GENERATED BY DEFAULT AS IDENTITY, PRIMARY KEY(id), NAME varchar2(20), COMPANY varchar2(10), AC_TYPE number,PAX_CAP NUMBER, CARGO_CAP, NUMBER, COST NUMBER, RUNWAY_LEN number, FUEL_PER_KM number);
create table FUEL(id number GENERATED BY DEFAULT AS IDENTITY, PRIMARY KEY(id), CAP number, AVL number, airline_id number, FOREIGN KEY(airline_id) REFERENCES AIRLINE(id) );
create table CO2(id number GENERATED BY DEFAULT AS IDENTITY, PRIMARY KEY(id), CAP number, AVL number, airline_id number, FOREIGN KEY(airline_id) REFERENCES AIRLINE(id) );
create table AC_OWNED(id number GENERATED BY DEFAULT AS IDENTITY, PRIMARY KEY(id), PURCHASED_AT DATE, AC_id number, AIRLINE_ID number, WEAR number, HOURS_M number, Inflight varchar2(1), SRC varchar2(4), DEPT varchar2(4), PAX_Occ number, CARGO_Occ number, FOREIGN KEY(AC_id) REFERENCES AC_OWNED(id), FOREIGN KEY(AIRLINE_ID) REFERENCES AIRLINE(ID));
create table AIRPORT(id number GENERATED BY DEFAULT AS IDENTITY, PRIMARY KEY(id), CODE varchar2(4), NAME varchar2(20), MAX_RUNWAY number);
create table ROUTES(id number GENERATED BY DEFAULT AS IDENTITY, PRIMARY KEY(id), SRC_apt number, DES_apt number, DIST number, PAX_DEMAND number, CARGO_DEMAND number);
create table HANGAR(id number GENERATED BY DEFAULT AS IDENTITY, PRIMARY KEY(id), PORT_id number, AIRLINE_ID number, AC_CAPACITY number, AC_OCCUPIED number, FOREIGN KEY(PORT_id) REFERENCES AIRPORT(id), FOREIGN KEY(AIRLINE_ID) REFERENCES AIRLINE(id));
create table HUB(id number GENERATED BY DEFAULT AS IDENTITY, PRIMARY KEY(id), PORT_id number, AIRLINE_ID number , FOREIGN KEY(PORT_id) REFERENCES AIRPORT(id), FOREIGN KEY(AIRLINE_ID) REFERENCES AIRLINE(id));
